In [1]:
import numpy as np

<h1>Algebra del MCO</h1>
<p style="font-size:20px">

Queremos estimar el siguiente modelo de regresión lineal:

$$
y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + e_i \quad \forall i = 1, ..., 5
$$

Es decir, contamos con 5 observaciones para realizar dicha estimación. Los datos son los siguientes:

$$
y = \begin{bmatrix} 3 \\ 1 \\ 8 \\ 3 \\ 5 \end{bmatrix} \quad
X = \begin{bmatrix} 1 & 3 & 5 \\ 1 & 1 & 4 \\ 1 & 5 & 6 \\ 1 & 2 & 4 \\ 1 & 4 & 6 \end{bmatrix}
$$

De forma matricial la ecuación a estimar sería,

$$
y = X\beta + e
$$

In [2]:
##definimos matrices X y Y dadas por el ejercicio
y=np.array([[3],[1],[8],[3],[5]])

x=np.array([[1, 3, 5],
            [1, 1, 4],
            [1, 5, 6],
            [1, 2, 4],
            [1, 4, 6]])


1. Obtenga la estimación de mínimos cuadrados ordinarios: $βˆ = (X'X)ˆ{-1} X'y$. Indique específicamente el valor para $β_0ˆ, β_1ˆ, β_2ˆ$.

In [3]:
x_t=x.T  ##calculamos x transpuesta
x_xt_inv=np.linalg.inv(x_t @ x)  ##(x'x)^-1
beta_hat= x_xt_inv @ (x_t @ y)   

print(beta_hat)

[[ 4. ]
 [ 2.5]
 [-1.5]]


Donde
$β_0ˆ $ es 4, $β_1ˆ $ es 2.5,$ β_2ˆ$ es -1.5.

2. Obtenga el vector de residuos eˆ = y − Xβˆ

In [4]:
y_hat= x @ beta_hat
e_hat=y-y_hat
print(e_hat.round(2))

[[-1. ]
 [ 0.5]
 [ 0.5]
 [-0. ]
 [-0. ]]


3. Obtenga el vector de predicción yˆ = Xβˆ. ¿Cuál es la predicción del modelo para la observación 3? 

Para la 3ra observacion, la prediccion es 7.5

In [5]:
print(y_hat[2])

[7.5]


4. Obtenga las matrices idempotentes P y M. Muestre las propiedades que se discutieron en
clases.

En los siguientes pasos obtenemos la matriz P y mostramos sus propiedades.

In [6]:
x_xt_inv=np.linalg.inv(x_t @ x)
p=x@ (x_xt_inv) @ x_t   ##calculamos p

## P es simetrica
p_t=p.T
print(r"1. P ES SIMETRICA porque p=p'")
print(p, '\n', 'es igual a ', '\n', p_t)

##P es idempotente
pp=p@p
print("\n",r" 2. P ES IDEMPOTENTE porque pp=p")
print(pp, '\n', 'es igual a ', '\n', p)

##tr(P)=k
print('\n',"3. La traza de P es un valor k=",np.trace(p).round(1))

1. P ES SIMETRICA porque p=p'
[[ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2  0.7 -0.3  0.2  0.2]
 [ 0.2 -0.3  0.7  0.2  0.2]
 [ 0.2  0.2  0.2  0.7 -0.3]
 [ 0.2  0.2  0.2 -0.3  0.7]] 
 es igual a  
 [[ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2  0.7 -0.3  0.2  0.2]
 [ 0.2 -0.3  0.7  0.2  0.2]
 [ 0.2  0.2  0.2  0.7 -0.3]
 [ 0.2  0.2  0.2 -0.3  0.7]]

  2. P ES IDEMPOTENTE porque pp=p
[[ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2  0.7 -0.3  0.2  0.2]
 [ 0.2 -0.3  0.7  0.2  0.2]
 [ 0.2  0.2  0.2  0.7 -0.3]
 [ 0.2  0.2  0.2 -0.3  0.7]] 
 es igual a  
 [[ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2  0.7 -0.3  0.2  0.2]
 [ 0.2 -0.3  0.7  0.2  0.2]
 [ 0.2  0.2  0.2  0.7 -0.3]
 [ 0.2  0.2  0.2 -0.3  0.7]]

 3. La traza de P es un valor k= 3.0


In [7]:
##Los autovalores de p son 1 y 0. k autovalores son 1 y n-k son 0
print('\n')
autovalores = np.linalg.eigvals(p)
print("4.Los autovalores de p son: ",autovalores.round(1))
print("\n","Hay k=3 autovalores iguales a 1. Hay n-k=5-3=2 autovalores iguales a 0.")

##rank(p)=k
rank = np.linalg.matrix_rank(p)
print("\n","5.El rango de p es:", rank)

##px1=x1 donde de modo que x=[x1 x2]
x1 = x[:, [0, 1]]
p_x1=p@x1
print('\n','6. X=[X1 X2] entonces PX1=X1')
print("\n",'PX1=',p_x1,'\n','es igual a','\n','X1=',x1)





4.Los autovalores de p son:  [0.+0.j 0.-0.j 1.+0.j 1.-0.j 1.+0.j]

 Hay k=3 autovalores iguales a 1. Hay n-k=5-3=2 autovalores iguales a 0.

 5.El rango de p es: 3

 6. X=[X1 X2] entonces PX1=X1

 PX1= [[1. 3.]
 [1. 1.]
 [1. 5.]
 [1. 2.]
 [1. 4.]] 
 es igual a 
 X1= [[1 3]
 [1 1]
 [1 5]
 [1 2]
 [1 4]]


In [8]:
##Py=xB^=y^
py=p@y
x_betahat=x@beta_hat
print('7.Py=xB^=y^')
print('py=',py,'\n','xB^=',x_betahat, '\n','y^=',y_hat)

7.Py=xB^=y^
py= [[4. ]
 [0.5]
 [7.5]
 [3. ]
 [5. ]] 
 xB^= [[4. ]
 [0.5]
 [7.5]
 [3. ]
 [5. ]] 
 y^= [[4. ]
 [0.5]
 [7.5]
 [3. ]
 [5. ]]


En los siguientes pasos obtenemos la matriz m y mostramos sus propiedades

In [9]:
I=np.eye((5))
m=I-p   ##calculamos m

## M es simetrica
m_t=m.T
print(r"1. M ES SIMETRICA porque m=m'")
print(m, '\n', 'es igual a ', '\n', m_t)

##M es idempotente
mm= m @ m
print("\n",r" 2. M ES IDEMPOTENTE porque mm=m")
print(mm, '\n', 'es igual a ', '\n', m)


1. M ES SIMETRICA porque m=m'
[[ 0.8 -0.2 -0.2 -0.2 -0.2]
 [-0.2  0.3  0.3 -0.2 -0.2]
 [-0.2  0.3  0.3 -0.2 -0.2]
 [-0.2 -0.2 -0.2  0.3  0.3]
 [-0.2 -0.2 -0.2  0.3  0.3]] 
 es igual a  
 [[ 0.8 -0.2 -0.2 -0.2 -0.2]
 [-0.2  0.3  0.3 -0.2 -0.2]
 [-0.2  0.3  0.3 -0.2 -0.2]
 [-0.2 -0.2 -0.2  0.3  0.3]
 [-0.2 -0.2 -0.2  0.3  0.3]]

  2. M ES IDEMPOTENTE porque mm=m
[[ 0.8 -0.2 -0.2 -0.2 -0.2]
 [-0.2  0.3  0.3 -0.2 -0.2]
 [-0.2  0.3  0.3 -0.2 -0.2]
 [-0.2 -0.2 -0.2  0.3  0.3]
 [-0.2 -0.2 -0.2  0.3  0.3]] 
 es igual a  
 [[ 0.8 -0.2 -0.2 -0.2 -0.2]
 [-0.2  0.3  0.3 -0.2 -0.2]
 [-0.2  0.3  0.3 -0.2 -0.2]
 [-0.2 -0.2 -0.2  0.3  0.3]
 [-0.2 -0.2 -0.2  0.3  0.3]]


In [10]:
##matriz de anulacion
mx=m@x
print('\n',"3. MX=0 : ",mx.round(2))

##tr(M)=n-k
print('\n',"4. La traza de M es un valor n-k=",np.trace(m).round(1))

##Los autovalores de m son 1 y 0. n-k autovalores son 1 y k son 0
print('\n')
autovalores = np.linalg.eigvals(m)
print("5.Los autovalores de m son: ",autovalores.round(1))
print("\n","Hay n-k=2 autovalores iguales a 1. Hay k=3 autovalores iguales a 0.")




 3. MX=0 :  [[ 0.  0.  0.]
 [ 0.  0.  0.]
 [-0. -0. -0.]
 [ 0.  0.  0.]
 [-0. -0. -0.]]

 4. La traza de M es un valor n-k= 2.0


5.Los autovalores de m son:  [ 1.+0.j  1.+0.j  0.+0.j -0.+0.j -0.-0.j]

 Hay n-k=2 autovalores iguales a 1. Hay k=3 autovalores iguales a 0.


5. Obtenga el vector de predicción yˆ = P y, compruebe si este resultado es igual al resultado
obtenido en el literal 3).

In [12]:
y_hat2=p @ y

print(y_hat, "es igual a ")
print(y_hat2)

[[4. ]
 [0.5]
 [7.5]
 [3. ]
 [5. ]] es igual a 
[[4. ]
 [0.5]
 [7.5]
 [3. ]
 [5. ]]


6. Obtenga el vector de residuos eˆ = My, compruebe si este resultado es igual al del literal 2).

In [13]:
e_hat2=m @ y
print(e_hat.round(2), "es igual a ")
print(e_hat2.round(2))

[[-1. ]
 [ 0.5]
 [ 0.5]
 [-0. ]
 [-0. ]] es igual a 
[[-1. ]
 [ 0.5]
 [ 0.5]
 [ 0. ]
 [-0. ]]


Considere ahora la matriz 
$$
M_0 = I − ι(ι'ι)^{−1}ι'
$$
, donde ι es un vector n × 1 de 1.


7. Obtenga el producto M0y. Con base en ese resultado, ¿cuál es la funcion entonces de la
matriz M0?

In [14]:
iota=np.array([[1], [1], [1], [1], [1]])
iota_t=iota.T
iota_iota_t_inv=np.linalg.inv(iota_t @ iota)
I=np.eye(5)

M0=M0 = (I - iota @ iota_iota_t_inv @ iota_t).round(2)


M0_y=M0 @ y
print(M0_y)

[[-1.]
 [-3.]
 [ 4.]
 [-1.]
 [ 1.]]


8. Ahora, premultiplique la ecuación 2 por la matrix M0, y obtenga la fórmula para el estimador
de MCO de esta ecuación transformada. Ea decir,
$$M_0 y = M_ 0 Xβ + M_0 e $$
Llame =X2 = M0X, sea β2 el vector resultante de esta transformación.
¿Cuál es la dimensión del vector β? ¿Cuál es el resultado de M0e?

In [15]:
x = x[:,1:3]
x_t = x.T
xt_m0_x= np.linalg.inv(x_t @ M0 @ x)
beta_hat2=xt_m0_x @ x_t @ M0_y

print("B^_2 es=",beta_hat2.round(1))

print("Su dimensión es de 2x1")
m0_x2=M0 @ x
e_hat2= M0_y - m0_x2 @ beta_hat2
print("el resultado de M0e es igual a =\n", np.round(e_hat2,2))



B^_2 es= [[ 2.5]
 [-1.5]]
Su dimensión es de 2x1
el resultado de M0e es igual a =
 [[-1. ]
 [ 0.5]
 [ 0.5]
 [ 0. ]
 [-0. ]]


9. Usando los datos dados previamente, use la formula del literal anterior para obtener las estimaciones de los betas. ¿qué puede decir con respecto a las estimacion obtenidas previamente en el literal 1?


In [16]:
# β2 = (X2'X2)^(-1) X2'y2
beta2= xt_m0_x @ x_t @ M0_y
beta2 = beta2.reshape(2, 1)
print(beta2)
print(beta_hat)

[[ 2.5]
 [-1.5]]
[[ 4. ]
 [ 2.5]
 [-1.5]]


La diferencia es que el beta calculado con la ecuacion del literal anterior elimina la constante por eso el beta es de dimension 2x1 mientras que el beta calculado anteriormente es de 3x1.

10. ¿Cómo puede obtener la estimación para β0? Calcule.

In [25]:
p2 = np.linalg.inv(iota.T @ iota) @ iota.T
y_barra = p2 @ y
x_barra = p2 @ m0_x2

beta0 = y_barra - np.dot(x_barra,beta2)

print(beta0)

[[4.]]


11. Calcule $$β_0^ = ¯y − β_1ˆX_1¯ − β_2ˆX_2¯ $$

In [18]:
beta0_2 = y_barra - beta2[0] @ x_barra[:,0] - beta2[1] @ x_barra[:,1]
print(beta0_2)

[[4.]]


12. Calcule la suma de cuadrado totales $ T SS = y'M_0y$

In [19]:
y_t=y.T
tss=y_t @ M0 @ y
print(tss)

[[28.]]


13. Calcule la suma de cuadrado explicado ESS = β_2ˆ0X0
2M0X2βˆ
2

In [20]:
x2_t=m0_x2.T
ess = beta2.T @ x2_t @ M0 @ m0_x2 @ beta2
print("ESS:", ess)

ESS: [[26.5]]


14. Calcule la suma de cuadrado explicado RSS = ˆe' e

In [21]:
e_hat_t=e_hat.T
rss=(e_hat_t @ e_hat).round(2)
print(rss)

[[1.5]]


15. Calcule el R2 y el R2 ajustado

In [22]:
R2 = ess / tss

n = y.shape[0]
k = m0_x2.shape[1]
R2_adj = 1 - ((1 - R2) * (n - 1) / (n - k - 1))

print("R2=", R2.round(2))
print("R2 ajustado=",R2_adj.round(2))

R2= [[0.95]]
R2 ajustado= [[0.89]]


16. Siguiendo el algoritmo propuesto en el teorema FWL, desarrolle un codigo donde se evidencia
cada una de los tres paso, y finalmente se muestre la estimacion de β2.

In [23]:
x=np.array([[1, 3, 5],
            [1, 1, 4],
            [1, 5, 6],
            [1, 2, 4],
            [1, 4, 6]])

In [24]:
X1 = x[:, [0, 1]] 
FWLbeta1 = np.linalg.inv(X1.T @ X1) @ X1.T @ y
ee1 = y - X1 @ FWLbeta1
X2 = x[:, [2]] 
FWLbeta_x2 = np.linalg.inv(X1.T @ X1) @ X1.T @ X2
X2tilde = X2 - X1 @ FWLbeta_x2
FWLbeta_2 = np.linalg.inv(X2tilde.T @ X2tilde) @ X2tilde.T @ ee1

print(FWLbeta_2)

[[-1.5]]
